### ISSUE TITLE
Another barebones boilerplate will be really helpful

### ISSUE THREAD

**Issue by rajan-31** [mustafacagri/mevn-boilerplate#3]
First of all, thanks for your efforts.

- This boilerplate is a little complex for someone who is just getting started.
- It would be greatly appreciated if you could create another boilerplate with very basic Nuxt 3 and Express+MongoDB code to connect the client and server sides.
- Then this (current) boilerplate could be used as a reference for further development.

**Comment by mustafacagri** [comment]
hey @rajan-31, actually you can clean this a bit up to use only the Nuxt 3 + Express + MongoDB parts. Please ping me if you stuck at any point. Thanks

**Comment by rajan-31** [comment]
Yeah, I got it. Thanks.
